# This file was generated by GoReleaser. DO NOT EDIT.
cask "payk" do
  version "0.2.0"

  on_macos do
    on_intel do
      sha256 "12050b801a755e176e96562c33d8d80f3afcb250330596a881f98fd96e890f1b"
      url "https://github.com/yusupkhemraev/payk/releases/download/v#{version}/payk_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "abad64fde580cf947384cf15173cdd7ee7ed223da213510fc4acfc4e22f8aa84"
      url "https://github.com/yusupkhemraev/payk/releases/download/v#{version}/payk_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "850ebbc959fcbf0a0239ddfd9cfed4384ba864585dfa3dfc524aaa15b8456f00"
      url "https://github.com/yusupkhemraev/payk/releases/download/v#{version}/payk_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "8d452a3ba01467e46465d801f8aab1157211c785c174d011e62a1e0b10ae2df3"
      url "https://github.com/yusupkhemraev/payk/releases/download/v#{version}/payk_#{version}_linux_arm64.tar.gz"
    end
  end

  name "payk"
  desc "Keyboard-first TUI HTTP client"
  homepage "https://github.com/yusupkhemraev/payk"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "payk"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/payk"]
    end
  end

  # No zap stanza required

end
