# This file was generated by GoReleaser. DO NOT EDIT.
cask "payk" do
  version "0.1.2"

  on_macos do
    on_intel do
      sha256 "b7b58feb83ef1aadcc8701d360d67a607af48c4b33d231e1af66c674442774a7"
      url "https://github.com/yusupkhemraev/payk/releases/download/v#{version}/payk_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "4333dfa4d0e4ef96f89ed1e4a82b44b743b173672d937e0cd588d3481aa5cf68"
      url "https://github.com/yusupkhemraev/payk/releases/download/v#{version}/payk_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "586ad9a9c1b12115efa616491c5211b727c768c52ecefdff82432e64a48cc66f"
      url "https://github.com/yusupkhemraev/payk/releases/download/v#{version}/payk_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "973d8620a2ff774a37596deda8b8a2fb3ceb1151568ae2417b5d09334356841f"
      url "https://github.com/yusupkhemraev/payk/releases/download/v#{version}/payk_#{version}_linux_arm64.tar.gz"
    end
  end

  name "payk"
  desc "Keyboard-first TUI HTTP client"
  homepage "https://github.com/yusupkhemraev/payk"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "payk"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/payk"]
    end
  end

  # No zap stanza required

end
