# This file was generated by GoReleaser. DO NOT EDIT.
cask "payk" do
  version "0.1.1"

  on_macos do
    on_intel do
      sha256 "7b6530b943f185d9e1708fd61aba2bc3e1e4e20ef45e52543f60f914c4afe62f"
      url "https://github.com/yusupkhemraev/payk/releases/download/v#{version}/payk_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "f831a56ff4c603ec8fc9829630f974e34b90ee39d07254bc5496814d6ce94841"
      url "https://github.com/yusupkhemraev/payk/releases/download/v#{version}/payk_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "2fa42b322035dfd17a0e4a1b5adeef6bcf5cf1aac796dd143df41b14cdaff17d"
      url "https://github.com/yusupkhemraev/payk/releases/download/v#{version}/payk_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "010bc323116d5463aa271d3ff9d6ec46146b9c214b4b0d9c6df5e16f5cf014f7"
      url "https://github.com/yusupkhemraev/payk/releases/download/v#{version}/payk_#{version}_linux_arm64.tar.gz"
    end
  end

  name "payk"
  desc "Keyboard-first TUI HTTP client"
  homepage "https://github.com/yusupkhemraev/payk"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "payk"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/payk"]
    end
  end

  # No zap stanza required

end
